### ISSUE TITLE
2 tinfoil HB/repo: any particular reason ?

### ISSUE THREAD

**Issue by tiliarou** [digableinc/tinfoil#1]
That's not really an issue but a very confusing change indeed...
Why was it renamed to tinfoil whereas we already have XorTroll's one ?

**Comment by blawar** [comment]
XorTroll does not own a trademark on the name Tinfoil, and XorTroll has not even released anything under the name.

**Comment by tiliarou** [comment]
Noted. Not meaning any offence or flaming. Thanks for taking time to answer.
Still confusing though, even if there was no "release" per say.

**Comment by james-d-elliott** [comment]
I don't believe you own a trademark on it either, what's the registration number?

**Comment by gerd2002** [comment]
the only trademark registered under the name tinfoil in the US is http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4803:wtzn5u.2.2

i don't believe that is this tinfoil.

**Comment by danielbernard** [comment]
> the only trademark registered under the name tinfoil in the US is http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4803:wtzn5u.2.2
> 
> i don't believe that is this tinfoil.

Since TSEE searches expire, to help others find the reference, 
* Registration Number: 4756604
* IC 009. US 021 023 026 036 038. G & S: Eyewear, namely, sunglasses and spectacles and their parts and accessories, namely, replacement lenses, ear stems, frames, nose pieces and foam strips; cases specifically adapted for eyewear and their parts and accessories. FIRST USE: 20140424. FIRST USE IN COMMERCE: 20140424

Registered by Oakley. So obviously not for this application.
